# Generated by Django 4.2 on 2024-05-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='launch_country',
        ),
    ]
