# Generated by Django 4.2 on 2024-05-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_satellite_launch_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='launch_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.launchcountry'),
        ),
    ]
